/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almacenes.vistas;

import almacenes.conectorDB.DatabaseUtils;
import almacenes.model.Configuracion;
import almacenes.model.Permiso;
import dao.SistemaDAO;
import dao.SistemaDAOImpl;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author georgeguitar
 */
public class FormMenu extends javax.swing.JFrame {
    private DatabaseUtils databaseUtils;
    private Connection connectionDB;
    private String idUsuario;
    SistemaDAO sistemaDAO;

    private static final String MENU_PROCESOS = "menu_procesos";
    private static final String MENU_VENTAS = "menu_ventas";
    private static final String MENU_COMPRAS = "menu_compras";
    private static final String CAJA_INICIAL = "caja_inicial";
    private static final String CERRAR_CAJA = "cerrar_caja";
        
    private static final String MENU_CONFIGURACION = "menu_configuracion";
    private static final String MENU_CONFIGURACION_MARCAS = "menu_configuracion_marcas";
    private static final String MENU_CONFIGURACION_PROCEDENCIA = "menu_configuracion_procedencia";
    private static final String MENU_CONFIGURACION_RUBROS = "menu_configuracion_rubros";
    private static final String MENU_CONFIGURACION_UNIDAD_MEDIDA = "menu_configuracion_unidad_medida";
    private static final String MENU_CONFIGURACION_PRODUCTOS = "menu_configuracion_productos";
    
    private static final String MENU_ADMINISTRACION = "menu_administracion";
    
    private static final String MENU_INFORMES = "menu_informes";
    //private static final String MENU_PROCESOS_VENTAS = "menu_procesos_ventas";
    
    
    
    private static final int REPORTE_UNO = 1;
    private static final int REPORTE_DOS = 2;
    private static final int REPORTE_TRES = 3;
    private static final int REPORTE_CUATRO = 4;
    
    private static byte idLugar = 1;
    /**
     * Creates new form Menu
     */
    public FormMenu() {
        initComponents();
    }

    public FormMenu(Connection _connectionDB, String _idUsuario) {
        initComponents();
        this.databaseUtils = new DatabaseUtils();
        this.connectionDB = _connectionDB;
        sistemaDAO = new SistemaDAOImpl(connectionDB);
        this.idUsuario = _idUsuario;
        ocultarMenus();
        habilitarMenusUsuario();
        jMenuRestaurarDB.setVisible(false);
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuProcesos = new javax.swing.JMenu();
        jMenuVentas = new javax.swing.JMenuItem();
        jMenuCompras = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmenuCajaInicial = new javax.swing.JMenuItem();
        jmenuCerrarCaja = new javax.swing.JMenuItem();
        jmAnularTrans = new javax.swing.JMenuItem();
        jmenuPendientesCobro = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenuMarcas = new javax.swing.JMenuItem();
        jMenuProcedencia = new javax.swing.JMenuItem();
        jMenuRubros = new javax.swing.JMenuItem();
        jMenuUnidadMedida = new javax.swing.JMenuItem();
        jMenuProductos = new javax.swing.JMenuItem();
        jmenuCliente = new javax.swing.JMenuItem();
        jmenuProveedor = new javax.swing.JMenuItem();
        jMenuAdministracion = new javax.swing.JMenu();
        jMenuStockInicial = new javax.swing.JMenuItem();
        jmenuIngresos = new javax.swing.JMenuItem();
        jmenuEgresos = new javax.swing.JMenuItem();
        jmenuUsers = new javax.swing.JMenuItem();
        jmenuCodigoControl = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuBackupDB = new javax.swing.JMenuItem();
        jMenuRestaurarDB = new javax.swing.JMenuItem();
        jMenuConfiguraciones = new javax.swing.JMenuItem();
        jMenuInformes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuStockProductos = new javax.swing.JMenuItem();
        jmenuMovimientoCajaGeneral = new javax.swing.JMenuItem();
        jmenuEntregas = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmenuLibroVentas = new javax.swing.JMenuItem();
        jmenuArqueos = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_don_piston.png"))); // NOI18N

        jlUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlUsuario.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlUsuario)))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jButton1.setToolTipText("Salir");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jMenuArchivo.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem1);

        jMenuBar1.add(jMenuArchivo);

        jMenuProcesos.setText("Procesos");

        jMenuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.png"))); // NOI18N
        jMenuVentas.setText("Ventas");
        jMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVentasActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuVentas);

        jMenuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compras.png"))); // NOI18N
        jMenuCompras.setText("Compras");
        jMenuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuComprasActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuCompras);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/credito.png"))); // NOI18N
        jMenuItem3.setText("Credito Ventas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuItem3);

        jmenuCajaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja_inicial.png"))); // NOI18N
        jmenuCajaInicial.setText("Caja Inicial");
        jmenuCajaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCajaInicialActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmenuCajaInicial);

        jmenuCerrarCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrar_caja.png"))); // NOI18N
        jmenuCerrarCaja.setText("Cerrar Caja");
        jmenuCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCerrarCajaActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmenuCerrarCaja);

        jmAnularTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jmAnularTrans.setText("Anular Trans");
        jmAnularTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAnularTransActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmAnularTrans);

        jmenuPendientesCobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pago_transaccion.png"))); // NOI18N
        jmenuPendientesCobro.setText("Pendientes Cobro");
        jmenuPendientesCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuPendientesCobroActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmenuPendientesCobro);

        jMenuItem5.setText("Credito X Facturar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuItem5);

        jMenuBar1.add(jMenuProcesos);

        jMenuConfiguracion.setText("Configuración");

        jMenuMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marca.png"))); // NOI18N
        jMenuMarcas.setText("Marcas");
        jMenuMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMarcasActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuMarcas);

        jMenuProcedencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/procedencia.png"))); // NOI18N
        jMenuProcedencia.setText("Procedencia");
        jMenuProcedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProcedenciaActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuProcedencia);

        jMenuRubros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rubro.png"))); // NOI18N
        jMenuRubros.setText("Rubros");
        jMenuRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRubrosActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuRubros);

        jMenuUnidadMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unidadMedida.png"))); // NOI18N
        jMenuUnidadMedida.setText("Unidad Medida");
        jMenuUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUnidadMedidaActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuUnidadMedida);

        jMenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos.png"))); // NOI18N
        jMenuProductos.setText("Productos");
        jMenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductosActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuProductos);

        jmenuCliente.setText("Clientes");
        jmenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuClienteActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jmenuCliente);

        jmenuProveedor.setText("Proveedores");
        jmenuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuProveedorActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jmenuProveedor);

        jMenuBar1.add(jMenuConfiguracion);

        jMenuAdministracion.setText("Administración");

        jMenuStockInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Configurar.png"))); // NOI18N
        jMenuStockInicial.setText("Ajuste Stock");
        jMenuStockInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStockInicialActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuStockInicial);

        jmenuIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingreso.png"))); // NOI18N
        jmenuIngresos.setText("Ingresos");
        jmenuIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuIngresosActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jmenuIngresos);

        jmenuEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        jmenuEgresos.setText("Egresos");
        jmenuEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEgresosActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jmenuEgresos);

        jmenuUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add-user-icon.png"))); // NOI18N
        jmenuUsers.setText("Usuarios");
        jmenuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuUsersActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jmenuUsers);

        jmenuCodigoControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codigo_control.png"))); // NOI18N
        jmenuCodigoControl.setText("Codigo Control Impuestos");
        jmenuCodigoControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCodigoControlActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jmenuCodigoControl);
        jMenuAdministracion.add(jSeparator1);

        jMenuBackupDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backup.png"))); // NOI18N
        jMenuBackupDB.setText("Backup DB");
        jMenuBackupDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBackupDBActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuBackupDB);

        jMenuRestaurarDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/restore_db.png"))); // NOI18N
        jMenuRestaurarDB.setText("Restaurar DB");
        jMenuRestaurarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRestaurarDBActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuRestaurarDB);

        jMenuConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/setup.png"))); // NOI18N
        jMenuConfiguraciones.setText("Configuraciones");
        jMenuConfiguraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfiguracionesActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuConfiguraciones);

        jMenuBar1.add(jMenuAdministracion);

        jMenuInformes.setText("Informes");

        jMenuItem2.setText("Reporte Ventas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItem2);

        jMenuStockProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock.png"))); // NOI18N
        jMenuStockProductos.setText("Stock Productos");
        jMenuStockProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStockProductosActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuStockProductos);

        jmenuMovimientoCajaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/movimiento_caja.png"))); // NOI18N
        jmenuMovimientoCajaGeneral.setText("Movimiento Caja General");
        jmenuMovimientoCajaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuMovimientoCajaGeneralActionPerformed(evt);
            }
        });
        jMenuInformes.add(jmenuMovimientoCajaGeneral);

        jmenuEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entregas.png"))); // NOI18N
        jmenuEntregas.setText("Reporte Entregas");
        jmenuEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEntregasActionPerformed(evt);
            }
        });
        jMenuInformes.add(jmenuEntregas);

        jMenuItem4.setText("Impresion Directa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItem4);

        jmenuLibroVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura.png"))); // NOI18N
        jmenuLibroVentas.setText("Libro Ventas");
        jmenuLibroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuLibroVentasActionPerformed(evt);
            }
        });
        jMenuInformes.add(jmenuLibroVentas);

        jmenuArqueos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arqueos.png"))); // NOI18N
        jmenuArqueos.setText("Lista Arqueos");
        jmenuArqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuArqueosActionPerformed(evt);
            }
        });
        jMenuInformes.add(jmenuArqueos);

        jMenuBar1.add(jMenuInformes);

        jMenuAyuda.setText("Ayuda");
        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        salir();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVentasActionPerformed
//        FormProcesosVentas procesosVentas = new almacenes.vistas.FormProcesosVentas(connectionDB);
//        procesosVentas.setVariable("hola");
//        procesosVentas.setVisible(true);
        int idTipoTransaccion = 2;
        int idTipoTransaccionEntrega = 8;
        FormTransaccion formTrans = new FormTransaccion(connectionDB, 
                                            idTipoTransaccion, idTipoTransaccionEntrega, 
                                            idUsuario, idLugar);
        formTrans.setVisible(true);
    }//GEN-LAST:event_jMenuVentasActionPerformed

    private void jMenuMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMarcasActionPerformed
        FormMarca fmarca = new FormMarca(connectionDB);
        fmarca.setVisible(true);
    }//GEN-LAST:event_jMenuMarcasActionPerformed

    private void jMenuProcedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProcedenciaActionPerformed
        FormProcedencia fprocedencia = new FormProcedencia(connectionDB);
        fprocedencia.setVisible(true);
    }//GEN-LAST:event_jMenuProcedenciaActionPerformed

    private void jMenuRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRubrosActionPerformed
        FormRubro frubro = new FormRubro(connectionDB);
        frubro.setVisible(true);
    }//GEN-LAST:event_jMenuRubrosActionPerformed

    private void jMenuUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUnidadMedidaActionPerformed
        FormUnidadMedida fUmed = new FormUnidadMedida(connectionDB);
        fUmed.setVisible(true);
    }//GEN-LAST:event_jMenuUnidadMedidaActionPerformed

    private void jMenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductosActionPerformed
        FormProducto fprod = new FormProducto(connectionDB, idUsuario);
        fprod.setVisible(true);
    }//GEN-LAST:event_jMenuProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        salir();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new ElegirFechasImprimirReportes(this, false, connectionDB, idUsuario, REPORTE_UNO).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuComprasActionPerformed
        int idTipoTransaccion = 1;// nro para compras
        int idTipoTransaccionEntrega = 7;
        FormTransaccion formTrans = new FormTransaccion(connectionDB, 
                                        idTipoTransaccion, idTipoTransaccionEntrega, 
                                        idUsuario, idLugar);
        formTrans.setVisible(true);
    }//GEN-LAST:event_jMenuComprasActionPerformed

    private void jMenuStockInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStockInicialActionPerformed
        int idTipoTransaccion = 6;// stock inicial
        int idTipoTransaccionEntrega = 7;
        FormTransaccion formTrans = new FormTransaccion(connectionDB, 
                                        idTipoTransaccion, idTipoTransaccionEntrega, 
                                        idUsuario, idLugar);
        formTrans.setVisible(true);
    }//GEN-LAST:event_jMenuStockInicialActionPerformed

    private void jMenuStockProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStockProductosActionPerformed
        FormStockProducto fStock = new FormStockProducto(connectionDB, idLugar);
        fStock.setVisible(true);
    }//GEN-LAST:event_jMenuStockProductosActionPerformed

    private void jmenuCajaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCajaInicialActionPerformed
        FormCajaInicial fcajaIn = new FormCajaInicial(connectionDB, idUsuario, idLugar);
        fcajaIn.setVisible(true);
    }//GEN-LAST:event_jmenuCajaInicialActionPerformed

    private void jmenuCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCerrarCajaActionPerformed
        FormArqueoCaja formArq = new FormArqueoCaja(connectionDB, idUsuario, idLugar);
        formArq.setVisible(true);
                
    }//GEN-LAST:event_jmenuCerrarCajaActionPerformed

    private void jmenuEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEntregasActionPerformed
        new ElegirFechasImprimirReportes(this, false, connectionDB, idUsuario, REPORTE_DOS).setVisible(true);
    }//GEN-LAST:event_jmenuEntregasActionPerformed

    private void jmAnularTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAnularTransActionPerformed
        FormAnularTransaccion fAnular = new FormAnularTransaccion(connectionDB, idUsuario);
        fAnular.setVisible(true);
    }//GEN-LAST:event_jmAnularTransActionPerformed

    private void jmenuIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuIngresosActionPerformed
        String tipoCuenta = "I";
        int idTipoTransaccion = 5;
        FormIngresosEgresos fie = new FormIngresosEgresos(connectionDB, tipoCuenta, idLugar, idUsuario, idTipoTransaccion);
        fie.setVisible(true);
        
    }//GEN-LAST:event_jmenuIngresosActionPerformed

    private void jmenuEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEgresosActionPerformed
        String tipoCuenta = "E";
        int idTipoTransaccion = 4;
        FormIngresosEgresos fie = new FormIngresosEgresos(connectionDB, tipoCuenta, idLugar, idUsuario, idTipoTransaccion);
        fie.setVisible(true);
    }//GEN-LAST:event_jmenuEgresosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new FormImpresionDirecta(this, false, connectionDB, idUsuario).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuBackupDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBackupDBActionPerformed
        try {
            Configuracion configuracion = sistemaDAO.getGestionConfiguraciones();
            if (configuracion.getRutaProgramasPG() == null) {
                JOptionPane.showMessageDialog( null, "¡No existe la ruta del programa para hacer backup! \n\n" + 
                        "¡Vaya al menu de configurarión para definir una ruta!" , "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                new FormBackupDB(connectionDB, idUsuario).setVisible(true);             
            }
        } catch (Exception ex){
            Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
        };
    }//GEN-LAST:event_jMenuBackupDBActionPerformed

    private void jMenuRestaurarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRestaurarDBActionPerformed
        new FormRestaurarDB(connectionDB, idUsuario).setVisible(true);
    }//GEN-LAST:event_jMenuRestaurarDBActionPerformed

    private void jMenuConfiguracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConfiguracionesActionPerformed
        try {
            new FormConfiguraciones(connectionDB, idUsuario).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuConfiguracionesActionPerformed

    private void jmenuLibroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuLibroVentasActionPerformed
        FormLibroVentas fLibroVentas = new FormLibroVentas(connectionDB);
        fLibroVentas.setVisible(true);
    }//GEN-LAST:event_jmenuLibroVentasActionPerformed

    private void jmenuArqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuArqueosActionPerformed
        FormArqueos fArq = new FormArqueos(connectionDB);
        fArq.setVisible(true);
    }//GEN-LAST:event_jmenuArqueosActionPerformed

    private void jmenuMovimientoCajaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuMovimientoCajaGeneralActionPerformed
        new ElegirFechasImprimirReportes(this, false, connectionDB, idUsuario, REPORTE_CUATRO).setVisible(true);
    }//GEN-LAST:event_jmenuMovimientoCajaGeneralActionPerformed

    private void jmenuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuUsersActionPerformed
        FormUsuario fus = new FormUsuario(connectionDB);
        fus.setVisible(true);
    }//GEN-LAST:event_jmenuUsersActionPerformed

    private void jmenuCodigoControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCodigoControlActionPerformed
        FormValidarCodigoCotrol cod = new FormValidarCodigoCotrol();
        cod.setVisible(true);
    }//GEN-LAST:event_jmenuCodigoControlActionPerformed

    private void jmenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuClienteActionPerformed
        String tipo = "C";
        FormClienteProveedor formcli = new FormClienteProveedor(connectionDB, tipo);
        formcli.setVisible(true);
    }//GEN-LAST:event_jmenuClienteActionPerformed

    private void jmenuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuProveedorActionPerformed
        String tipo = "P";
        FormClienteProveedor formcli = new FormClienteProveedor(connectionDB, tipo);
        formcli.setVisible(true);
    }//GEN-LAST:event_jmenuProveedorActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int idTipoTransaccion = 3; //pedidos
        int idTipoTransaccionEntrega = 8; //entrega
        FormTransaccion formTrans = new FormTransaccion(connectionDB, 
                                            idTipoTransaccion, idTipoTransaccionEntrega, 
                                            idUsuario, idLugar);
        formTrans.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmenuPendientesCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuPendientesCobroActionPerformed
        int idTipoTransaccion = 3;// pedidos
        FormPendientesPago pend = new FormPendientesPago(connectionDB, idTipoTransaccion, idUsuario);
        pend.setVisible(true);
    }//GEN-LAST:event_jmenuPendientesCobroActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FormFacturaCredito ffc = new FormFacturaCredito(connectionDB);
        ffc.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void salir() {
        this.databaseUtils.close(connectionDB);
        System.exit(0);
    }
    
    private void habilitarMenusUsuario() {
        List<Permiso> permisosUsuario = new ArrayList<Permiso>();
        permisosUsuario = sistemaDAO.getPermisosUsuario(this.idUsuario);
        for (Permiso permiso : permisosUsuario) {
            if (permiso.getNombrePermiso().equals(MENU_PROCESOS)) {
                jMenuProcesos.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION)) {
                jMenuConfiguracion.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_ADMINISTRACION)) {
                jMenuAdministracion.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_INFORMES)) {
                jMenuInformes.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION_MARCAS)) {
                jMenuMarcas.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION_PROCEDENCIA)) {
                jMenuProcedencia.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION_RUBROS)) {
                jMenuRubros.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION_UNIDAD_MEDIDA)) {
                jMenuUnidadMedida.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION_PRODUCTOS)) {
                jMenuProductos.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_COMPRAS)) {
                jMenuCompras.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_VENTAS)) {
                jMenuVentas.setVisible(true);
            }
        }
        
        jlUsuario.setText("Usuario: " + idUsuario);
    }
    
    private void ocultarMenus() {
        jMenuConfiguracion.setVisible(false);
        jMenuAdministracion.setVisible(false);
        jMenuInformes.setVisible(false);
        jMenuMarcas.setVisible(false);
        jMenuProcedencia.setVisible(false); 
        jMenuProcesos.setVisible(false);
        jMenuProductos.setVisible(false);
        jMenuRubros.setVisible(false);
        jMenuUnidadMedida.setVisible(false);
        jMenuVentas.setVisible(false);
        jMenuCompras.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAdministracion;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuItem jMenuBackupDB;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCompras;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenuItem jMenuConfiguraciones;
    private javax.swing.JMenu jMenuInformes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuMarcas;
    private javax.swing.JMenuItem jMenuProcedencia;
    private javax.swing.JMenu jMenuProcesos;
    private javax.swing.JMenuItem jMenuProductos;
    private javax.swing.JMenuItem jMenuRestaurarDB;
    private javax.swing.JMenuItem jMenuRubros;
    private javax.swing.JMenuItem jMenuStockInicial;
    private javax.swing.JMenuItem jMenuStockProductos;
    private javax.swing.JMenuItem jMenuUnidadMedida;
    private javax.swing.JMenuItem jMenuVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JMenuItem jmAnularTrans;
    private javax.swing.JMenuItem jmenuArqueos;
    private javax.swing.JMenuItem jmenuCajaInicial;
    private javax.swing.JMenuItem jmenuCerrarCaja;
    private javax.swing.JMenuItem jmenuCliente;
    private javax.swing.JMenuItem jmenuCodigoControl;
    private javax.swing.JMenuItem jmenuEgresos;
    private javax.swing.JMenuItem jmenuEntregas;
    private javax.swing.JMenuItem jmenuIngresos;
    private javax.swing.JMenuItem jmenuLibroVentas;
    private javax.swing.JMenuItem jmenuMovimientoCajaGeneral;
    private javax.swing.JMenuItem jmenuPendientesCobro;
    private javax.swing.JMenuItem jmenuProveedor;
    private javax.swing.JMenuItem jmenuUsers;
    // End of variables declaration//GEN-END:variables
}
