/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almacenes.vistas;

import almacenes.conectorDB.DatabaseUtils;
import almacenes.model.Arqueo;
import almacenes.model.DetalleTransaccion;
import almacenes.model.ListaCaja;
import dao.ArqueoDAOImpl;
import dao.CajaDAOImpl;
import dao.DetalleTransaccionDAOImpl;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jcarlos.porcel
 */
public class FormArqueos extends javax.swing.JFrame {

    private DatabaseUtils databaseUtils;
    private Connection connectionDB;
    DefaultTableModel dtm;

    public FormArqueos() {
        initComponents();
    }
    
    public FormArqueos(Connection connectionDB) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.databaseUtils = new DatabaseUtils();
        this.connectionDB = connectionDB;
        
        headerTabla();

        iniciarComponentes();

    }
    
    public void headerTabla(){
        Font f = new Font("Times New Roman", Font.BOLD, 13);
        
        jtArqueos.getTableHeader().setFont(f);
        jtArqueos.getTableHeader().setBackground(Color.orange);
        
        jtCaja.getTableHeader().setFont(f);
        jtCaja.getTableHeader().setBackground(Color.orange);
        
        jtDetalleTransaccion.getTableHeader().setFont(f);
        jtDetalleTransaccion.getTableHeader().setBackground(Color.orange);
    }
    
    private void iniciarComponentes() {
        llenarMeses();
        llenarAnnos();
        vaciarTotales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcAnno = new javax.swing.JComboBox<>();
        jcMes = new javax.swing.JComboBox<>();
        jbBuscar = new javax.swing.JButton();
        jlTituloFormulario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtArqueos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jtxtTotalMes = new javax.swing.JTextField();
        jlTituloFormulario1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCaja = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jtxtTotalCaja = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtDetalleTransaccion = new javax.swing.JTable();
        jtxtTotalTransaccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jlTituloFormulario2 = new javax.swing.JLabel();
        jlTituloFormulario3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Mes");

        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Año");

        jcAnno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Search-icon.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jlTituloFormulario.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlTituloFormulario.setForeground(new java.awt.Color(153, 0, 51));
        jlTituloFormulario.setText("Lista Arqueos Mensuales");

        jtArqueos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Apertura", "Cierre", "Caja Inicial", "Caja Cierre", "Total", "Terminal", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtArqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtArqueosMouseClicked(evt);
            }
        });
        jtArqueos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtArqueosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtArqueos);
        if (jtArqueos.getColumnModel().getColumnCount() > 0) {
            jtArqueos.getColumnModel().getColumn(0).setMinWidth(0);
            jtArqueos.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtArqueos.getColumnModel().getColumn(0).setMaxWidth(0);
            jtArqueos.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Total Mes");

        jtxtTotalMes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jlTituloFormulario1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlTituloFormulario1.setForeground(new java.awt.Color(153, 0, 51));
        jlTituloFormulario1.setText("Caja");

        jtCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idTransaccion", "Nro.", "Fecha", "Movimiento", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCajaMouseClicked(evt);
            }
        });
        jtCaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCajaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtCaja);
        if (jtCaja.getColumnModel().getColumnCount() > 0) {
            jtCaja.getColumnModel().getColumn(0).setMinWidth(0);
            jtCaja.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtCaja.getColumnModel().getColumn(0).setMaxWidth(0);
            jtCaja.getColumnModel().getColumn(1).setMinWidth(40);
            jtCaja.getColumnModel().getColumn(1).setPreferredWidth(40);
            jtCaja.getColumnModel().getColumn(1).setMaxWidth(40);
        }

        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Total Caja");

        jtxtTotalCaja.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtDetalleTransaccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Simbolo", "Cantidad", "Importe Total"
            }
        ));
        jScrollPane3.setViewportView(jtDetalleTransaccion);
        if (jtDetalleTransaccion.getColumnModel().getColumnCount() > 0) {
            jtDetalleTransaccion.getColumnModel().getColumn(0).setResizable(false);
            jtDetalleTransaccion.getColumnModel().getColumn(0).setPreferredWidth(230);
            jtDetalleTransaccion.getColumnModel().getColumn(3).setResizable(false);
            jtDetalleTransaccion.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jtxtTotalTransaccion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("Total Movimiento");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_window.png"))); // NOI18N
        btnSalir.setText("Cerrar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jlTituloFormulario2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlTituloFormulario2.setForeground(new java.awt.Color(153, 0, 51));
        jlTituloFormulario2.setText("Caja");

        jlTituloFormulario3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlTituloFormulario3.setForeground(new java.awt.Color(153, 0, 51));
        jlTituloFormulario3.setText("Movimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(291, 291, 291)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxtTotalMes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxtTotalTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlTituloFormulario2)
                                .addGap(72, 72, 72)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtTotalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jlTituloFormulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTituloFormulario1)
                .addGap(138, 138, 138))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jlTituloFormulario3)
                    .addContainerGap(829, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloFormulario)
                    .addComponent(jlTituloFormulario1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jcAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTotalMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTituloFormulario2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTotalTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTotalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(230, 230, 230))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(457, Short.MAX_VALUE)
                    .addComponent(jlTituloFormulario3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(102, 102, 102)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        vaciarTotales();
        llenarTablaArqueos();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtArqueosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtArqueosKeyReleased
        seleccionarArqueo();
    }//GEN-LAST:event_jtArqueosKeyReleased

    private void jtArqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtArqueosMouseClicked
        seleccionarArqueo();
    }//GEN-LAST:event_jtArqueosMouseClicked

    private void jtCajaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCajaKeyReleased
        seleccionarDetalletransaccion();
    }//GEN-LAST:event_jtCajaKeyReleased

    private void jtCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCajaMouseClicked
        seleccionarDetalletransaccion();
    }//GEN-LAST:event_jtCajaMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormArqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormArqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormArqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormArqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormArqueos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JComboBox<String> jcAnno;
    private javax.swing.JComboBox<String> jcMes;
    private javax.swing.JLabel jlTituloFormulario;
    private javax.swing.JLabel jlTituloFormulario1;
    private javax.swing.JLabel jlTituloFormulario2;
    private javax.swing.JLabel jlTituloFormulario3;
    private javax.swing.JTable jtArqueos;
    private javax.swing.JTable jtCaja;
    private javax.swing.JTable jtDetalleTransaccion;
    private javax.swing.JTextField jtxtTotalCaja;
    private javax.swing.JTextField jtxtTotalMes;
    private javax.swing.JTextField jtxtTotalTransaccion;
    // End of variables declaration//GEN-END:variables

    private void llenarMeses() {
        jcMes.removeAllItems();

        ArrayList<String> lmeses = new ArrayList<String>();

        lmeses.add("ENERO");
        lmeses.add("FEBRERO");
        lmeses.add("MARZO");
        lmeses.add("ABRIL");
        lmeses.add("MAYO");
        lmeses.add("JUNIO");
        lmeses.add("JULIO");
        lmeses.add("AGOSTO");
        lmeses.add("SEPTIEMBRE");
        lmeses.add("NOVIEMBRE");
        lmeses.add("DICIEMBRE");

        for (byte i = 0; i < lmeses.size(); i++) {
            jcMes.addItem(lmeses.get(i).toString());
        }
    }
    
    public void seleccionarDetalletransaccion(){
        int fila = jtCaja.getSelectedRow();
        int idtransaccion = (int) jtCaja.getValueAt(fila, 0);
        
        llenarDetalleTransaccion(idtransaccion);
    }
    
    public void seleccionarArqueo(){
        int fila = jtArqueos.getSelectedRow();
        int idArqueo = (int) jtArqueos.getValueAt(fila, 0);
        
        llenarCaja(idArqueo);
        llenarDetalleTransaccion(0);
    }

    private void llenarAnnos() {
        jcAnno.removeAllItems();

        ArqueoDAOImpl fact = new ArqueoDAOImpl(connectionDB);
        ArrayList<Integer> lanno = fact.getListaAnnosArqueos();
        for (byte i = 0; i < lanno.size(); i++) {
            jcAnno.addItem(lanno.get(i).toString());
        }
    }
    
    public void llenarCaja(int idArqueo){
        double importeTotal = 0;
        
        CajaDAOImpl rub = new CajaDAOImpl(connectionDB);
        DecimalFormat df = new DecimalFormat("###,##0.00");

        ArrayList<ListaCaja> r = new ArrayList<ListaCaja>();

        r = rub.getListaCaja(idArqueo);

        dtm = (DefaultTableModel) this.jtCaja.getModel();
        dtm.setRowCount(0);

        jtCaja.setModel(dtm);

        Object[] fila = new Object[5];

        for (int i = 0; i < r.size(); i++) {
            fila[0] = r.get(i).getIdTransaccion();
            fila[1] = i;
            fila[2] = r.get(i).getFecha();
            fila[3] = r.get(i).getMovimiento();
            fila[4] = df.format(r.get(i).getImporteCaja());
            importeTotal = importeTotal + r.get(i).getImporteCaja();
            
            dtm.addRow(fila);
        }
        
        jtxtTotalCaja.setText(df.format(importeTotal).toString());

        TableColumnModel columnModel = jtCaja.getColumnModel();
        
        TableColumn colImpCaja = columnModel.getColumn(4);
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(jLabel1.RIGHT);
        
        colImpCaja.setCellRenderer(renderer);
        
        jtCaja.setModel(dtm);
    }
    
    public void llenarDetalleTransaccion(int idTransaccion){
        double importeTotal = 0;

        DetalleTransaccionDAOImpl rub = new DetalleTransaccionDAOImpl(connectionDB);
        DecimalFormat df = new DecimalFormat("###,##0.00");

        ArrayList<DetalleTransaccion> r = new ArrayList<DetalleTransaccion>();

        r = rub.getDetalleTransaccion(idTransaccion);

        dtm = (DefaultTableModel) this.jtDetalleTransaccion.getModel();
        dtm.setRowCount(0);

        jtDetalleTransaccion.setModel(dtm);

        Object[] fila = new Object[4];

        for (int i = 0; i < r.size(); i++) {
            fila[0] = r.get(i).getNombreProducto();
            fila[1] = r.get(i).getSimbolo();
            fila[2] = r.get(i).getCantidad();
            fila[3] = df.format(r.get(i).getValorTotal());
            importeTotal = importeTotal + r.get(i).getValorTotal();
            
            dtm.addRow(fila);
        }
        
        jtxtTotalTransaccion.setText(df.format(importeTotal).toString());

        TableColumnModel columnModel = jtDetalleTransaccion.getColumnModel();
        
        TableColumn colImpTotal = columnModel.getColumn(3);
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(jLabel1.RIGHT);
        
        colImpTotal.setCellRenderer(renderer);
        
        jtDetalleTransaccion.setModel(dtm);
    }
    
    public void llenarTablaArqueos() {
        double importeTotal = 0;

        ArqueoDAOImpl rub = new ArqueoDAOImpl(connectionDB);
        DecimalFormat df = new DecimalFormat("###,##0.00");

        ArrayList<Arqueo> r = new ArrayList<Arqueo>();

        byte mes = 0;
        int anno = 0;

        mes = (byte) (jcMes.getSelectedIndex() + 1);
        anno = Integer.parseInt(jcAnno.getSelectedItem().toString());

        r = rub.getListaArqueos(mes, anno);

        dtm = (DefaultTableModel) this.jtArqueos.getModel();
        dtm.setRowCount(0);

        jtArqueos.setModel(dtm);

        Object[] fila = new Object[8];

        for (int i = 0; i < r.size(); i++) {
            fila[0] = r.get(i).getId();
            fila[1] = r.get(i).getFechaApertura();
            fila[2] = r.get(i).getFechaCierre();
            fila[3] = df.format(r.get(i).getCajaInicial());
            fila[4] = df.format(r.get(i).getImporteCierre());
            fila[5] = df.format(r.get(i).getImporteCierre() - r.get(i).getCajaInicial());
            importeTotal = importeTotal + (r.get(i).getImporteCierre() - r.get(i).getCajaInicial());
            fila[6] = r.get(i).getIdTerminal();
            fila[7] = r.get(i).getUsuario();           

            dtm.addRow(fila);
        }
        
        jtxtTotalMes.setText(df.format(importeTotal).toString());

        TableColumnModel columnModel = jtArqueos.getColumnModel();
        
        TableColumn colImpApertura = columnModel.getColumn(3);
        TableColumn colImpCierre = columnModel.getColumn(4);
        TableColumn colImpTotal = columnModel.getColumn(5);
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(jLabel1.RIGHT);
        
        colImpApertura.setCellRenderer(renderer);
        colImpCierre.setCellRenderer(renderer);
        colImpTotal.setCellRenderer(renderer);
        
        jtArqueos.setModel(dtm);
    }
    
    public void vaciarTotales(){
        jtxtTotalMes.setText("");
    }

}
